services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    networks:
      - npm-network
      - proxy-network
    env_file: .env
    environment:
      - TZ="Europe/Moscow"
      # Uncomment this if IPv6 is not enabled on your host
      # - DISABLE_IPV6="true"
      - DB_POSTGRES_HOST="db"
      - DB_POSTGRES_PORT="5432"
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgresql:/var/lib/postgresql
    networks:
      - npm-network
      - proxy-network
      
networks:
  npm-network:
    name: npm-network
    driver: bridge
    external: false
  proxy-network:
    name: proxy-network
    driver: bridge
    external: true
